services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    # image: react-flask-app-api
    depends_on:
      - postgres_ppt
    ports:
      - "5008:5008"
    links:
      - postgres_ppt:postgres_ppt
    networks:
      - backend_ppt
  postgres_ppt:
    container_name: postgres_ppt
    image: postgres:latest
    ports:
      - "5438:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    
    expose:
      - "5432"
    networks:
      - backend_ppt
networks:
  backend_ppt:
    driver: bridge